# Site settings
title: "Stichting Falderie!"
email: "info@bureauhanna.nl"
description: > Falderie is een groep van muziekliefhebbers. Wij organiseren verwenconcerten voor mensen met een beperking in hun eigen omgeving. # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://stichtingfalderie.nl/" # the base hostname & protocol for your site

facebook_username: "stichtingfalderie"

twitter_username:
github_username: "stichtingfalderie"

# Build settings
markdown: kramdown
